name: BedWars1058-PartiesFix
author: Zyth
version: ${project.version}
description: Parties Fix Add-on for BedWars1058 Minigame.
main: com.andrei1058.bedwars.teamselector.Main
softdepend: [BedWars1058]
api-version: '1.13'